### ISSUE TITLE
Tambahkan dukungan 

### ISSUE THREAD

**Issue by Houjie80** [frizkyiman/friWrt-MyWrtBuilder#17]
Tolong Tambahkan dukungan untuk amlogic s905x4/advan at01..Terima kasih

**Comment by Houjie80** [comment]
Apakah ini bisa ganti kernel secara manual?

**Comment by frizkyiman** [comment]
tidak bisa, karna ini di comple dgn tool cain Image Builder yg sudah pre-compile dari sananya. tp klo punya source openwrt buat prosesor amlogic s905x4 tolong taruh disini, biar saya coba compilenya kalo bisa :)

**Comment by Houjie80** [comment]
https://github.com/armarchindo/ULO-Builder/releases

**Comment by frizkyiman** [comment]
oh iya ada ulo builder, nanti tak cobain, thankyou infonya :)

**Comment by Houjie80** [comment]
Sama sama

**Comment by Houjie80** [comment]
Maaf saya pemula dalam membuat fw openwrt..Saya mau tanya apakah bisa mengganti file yg ada dalam openwrt??saya ingin mbuat wifi internal bisa on...Di fw bawaan setiap kali wifi di on kan..Maka tidak bisa masuk luci lagi
