### ISSUE TITLE
Led kedip amlogic

### ISSUE THREAD

**Issue by Houjie80** [frizkyiman/friWrt-MyWrtBuilder#20]
Tolong tambah kan ini di fw amlogic

https://github.com/Houjie80/gpio-hg680p/tree/3led

**Comment by Houjie80** [comment]
![Uploading IMG_20240504_195233.jpg…]()

**Comment by frizkyiman** [comment]
tidak terlalu di perlukan ini sih om, lagian nambah beban karna terus menerus ping ke host tertentu, dan bisa ada kesempatan bikin ping loop jd ganggu proccess yg lain.
#imho
